// Generates seed/dev-seed.sql — DEVELOPMENT-ONLY sample data (spec §33).
// Never run this against a production database. Password hashing here
// mirrors src/lib/auth/password.ts exactly (PBKDF2-SHA256, 210k
// iterations) so the generated users can log in for real.
import { writeFileSync } from "node:fs";
import { randomUUID, webcrypto } from "node:crypto";

const crypto = webcrypto;
const ITERATIONS = 210_000;

function toHex(buf) {
  return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const keyMaterial = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveBits"]
  );
  const derived = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations: ITERATIONS, hash: "SHA-256" },
    keyMaterial,
    256
  );
  return { hash: toHex(derived), salt: toHex(salt.buffer) };
}

function sqlStr(v) {
  if (v === null || v === undefined) return "NULL";
  return `'${String(v).replace(/'/g, "''")}'`;
}

function weightSuffix(g) {
  return g % 1000 === 0 ? `${g / 1000}KG` : String(g);
}

async function main() {
  const lines = [];
  lines.push("-- DEV-ONLY seed data. Generated by scripts/seed-dev.mjs. Do NOT run in production.");

  // --- Users ---
  const admin = { id: randomUUID(), email: "admin@tucaphe.vn", name: "Quản trị viên", password: "Admin@123456" };
  const emp1 = { id: randomUUID(), email: "nam@tucaphe.vn", name: "Nguyễn Văn Nam", password: "Employee@123456" };
  const emp2 = { id: randomUUID(), email: "lan@tucaphe.vn", name: "Trần Thị Lan", password: "Employee@123456" };

  for (const u of [admin, emp1, emp2]) {
    const { hash, salt } = await hashPassword(u.password);
    const role = u === admin ? "ADMIN" : "EMPLOYEE";
    lines.push(
      `INSERT INTO users (id, email, full_name, password_hash, password_salt, role, status) VALUES (${sqlStr(
        u.id
      )}, ${sqlStr(u.email)}, ${sqlStr(u.name)}, ${sqlStr(hash)}, ${sqlStr(salt)}, ${sqlStr(role)}, 'ACTIVE');`
    );
  }

  // --- Customers ---
  const customers = [
    { name: "Cà Phê Sáng Xanh", phone: "0901111222", province: "TP.HCM", address: "12 Nguyễn Huệ, Q1" },
    { name: "Quán Cóc Thị Trấn", phone: "0902222333", province: "Đà Lạt", address: "45 Trần Hưng Đạo" },
    { name: "Anh Minh", phone: "0903333444", province: "Hà Nội", address: "78 Kim Mã" },
    { name: "Chị Hương Coffee Shop", phone: "0904444555", province: "Đà Nẵng", address: "23 Bạch Đằng" },
    { name: "Nhà hàng Sen Việt", phone: "0905555666", province: "Cần Thơ", address: "9 Nguyễn Trãi" },
  ].map((c) => ({ ...c, id: randomUUID() }));

  for (const c of customers) {
    lines.push(
      `INSERT INTO customers (id, name, phone, address, province) VALUES (${sqlStr(c.id)}, ${sqlStr(
        c.name
      )}, ${sqlStr(c.phone)}, ${sqlStr(c.address)}, ${sqlStr(c.province)});`
    );
  }

  // --- Products + variants ---
  const products = [
    { code: "CB", name: "Crema Blend" },
    { code: "HR", name: "Honey Reserve" },
    { code: "PMB", name: "Phin Mộc Bản" },
  ].map((p) => ({ ...p, id: randomUUID() }));

  const forms = ["HAT", "BOT"];
  const packagings = ["TUI_XANH", "TUI_ZIP"];
  const weights = [250, 500, 1000];
  const basePriceByWeight = { 250: 75000, 500: 140000, 1000: 260000 };

  const variants = [];
  for (const p of products) {
    lines.push(
      `INSERT INTO products (id, name, slug, code, description) VALUES (${sqlStr(p.id)}, ${sqlStr(
        p.name
      )}, ${sqlStr(p.name.toLowerCase().replace(/\s+/g, "-") + "-" + p.code.toLowerCase())}, ${sqlStr(
        p.code
      )}, ${sqlStr(`Dòng cà phê ${p.name}`)});`
    );
    for (const form of forms) {
      for (const packaging of packagings) {
        for (const weight of weights) {
          const sku = `${p.code}-${form === "HAT" ? "H" : "B"}-${packaging === "TUI_XANH" ? "XANH" : "ZIP"}-${weightSuffix(
            weight
          )}`;
          const variant = {
            id: randomUUID(),
            productId: p.id,
            form,
            packaging,
            weight,
            sku,
            unitPrice: basePriceByWeight[weight],
            costPrice: Math.round(basePriceByWeight[weight] * 0.6),
          };
          variants.push(variant);
          lines.push(
            `INSERT INTO product_variants (id, product_id, form, packaging, weight_grams, sku, unit_price, cost_price) VALUES (${sqlStr(
              variant.id
            )}, ${sqlStr(variant.productId)}, ${sqlStr(variant.form)}, ${sqlStr(variant.packaging)}, ${
              variant.weight
            }, ${sqlStr(variant.sku)}, ${variant.unitPrice}, ${variant.costPrice});`
          );
          const stock = 50 + Math.floor(Math.random() * 100);
          lines.push(
            `INSERT INTO inventory (id, product_variant_id, sku, quantity_on_hand, low_stock_threshold) VALUES (${sqlStr(
              randomUUID()
            )}, ${sqlStr(variant.id)}, ${sqlStr(variant.sku)}, ${stock}, 10);`
          );
        }
      }
    }
  }

  // --- Sample orders + tasks (for manual QA) ---
  const order1Id = randomUUID();
  const order1Items = [variants[0], variants[3]];
  const order1Total = order1Items.reduce((s, v) => s + v.unitPrice * 2, 0);
  lines.push(
    `INSERT INTO orders (id, order_code, customer_id, customer_phone_snapshot, customer_address_snapshot, status, total_amount, created_by) VALUES (${sqlStr(
      order1Id
    )}, 'DH-DEV-0001', ${sqlStr(customers[0].id)}, ${sqlStr(customers[0].phone)}, ${sqlStr(
      customers[0].address
    )}, 'CONFIRMED', ${order1Total}, ${sqlStr(admin.id)});`
  );
  for (const v of order1Items) {
    lines.push(
      `INSERT INTO order_items (id, order_id, product_variant_id, sku, product_name, form, packaging, weight_grams, quantity, unit_price, line_total) VALUES (${sqlStr(
        randomUUID()
      )}, ${sqlStr(order1Id)}, ${sqlStr(v.id)}, ${sqlStr(v.sku)}, ${sqlStr(
        products.find((p) => p.id === v.productId).name
      )}, ${sqlStr(v.form)}, ${sqlStr(v.packaging)}, ${v.weight}, 2, ${v.unitPrice}, ${v.unitPrice * 2});`
    );
  }

  const order2Id = randomUUID();
  const order2Items = [variants[10]];
  const order2Total = order2Items.reduce((s, v) => s + v.unitPrice * 3, 0);
  lines.push(
    `INSERT INTO orders (id, order_code, customer_id, customer_phone_snapshot, customer_address_snapshot, status, total_amount, created_by) VALUES (${sqlStr(
      order2Id
    )}, 'DH-DEV-0002', ${sqlStr(customers[1].id)}, ${sqlStr(customers[1].phone)}, ${sqlStr(
      customers[1].address
    )}, 'CONFIRMED', ${order2Total}, ${sqlStr(admin.id)});`
  );
  for (const v of order2Items) {
    lines.push(
      `INSERT INTO order_items (id, order_id, product_variant_id, sku, product_name, form, packaging, weight_grams, quantity, unit_price, line_total) VALUES (${sqlStr(
        randomUUID()
      )}, ${sqlStr(order2Id)}, ${sqlStr(v.id)}, ${sqlStr(v.sku)}, ${sqlStr(
        products.find((p) => p.id === v.productId).name
      )}, ${sqlStr(v.form)}, ${sqlStr(v.packaging)}, ${v.weight}, 3, ${v.unitPrice}, ${v.unitPrice * 3});`
    );
  }

  const task1Id = randomUUID();
  lines.push(
    `INSERT INTO tasks (id, order_id, assigned_to, assigned_by, title, priority, status) VALUES (${sqlStr(
      task1Id
    )}, ${sqlStr(order1Id)}, ${sqlStr(emp1.id)}, ${sqlStr(admin.id)}, 'Đóng gói đơn hàng DH-DEV-0001', 'NORMAL', 'TODO');`
  );
  const checklistLabels = [
    `Đúng SKU ${order1Items[0].sku}`,
    `Đúng SKU ${order1Items[1].sku}`,
    "Dán tem sản phẩm",
    "Kiểm tra địa chỉ giao hàng",
  ];
  checklistLabels.forEach((label, idx) => {
    lines.push(
      `INSERT INTO task_checklists (id, task_id, label, is_required, sort_order) VALUES (${sqlStr(
        randomUUID()
      )}, ${sqlStr(task1Id)}, ${sqlStr(label)}, 1, ${idx});`
    );
  });

  writeFileSync("seed/dev-seed.sql", lines.join("\n") + "\n");
  console.log(`Generated seed/dev-seed.sql (${lines.length} statements)`);
  console.log("\nDev login accounts:");
  console.log(`  ADMIN:    ${admin.email} / ${admin.password}`);
  console.log(`  EMPLOYEE: ${emp1.email} / ${emp1.password}`);
  console.log(`  EMPLOYEE: ${emp2.email} / ${emp2.password}`);
}

main();
