-- Dữ liệu mẫu ban đầu — đúng theo PRODUCTS_SEED trong js/products-data.js.
-- Chạy 1 LẦN sau khi tạo schema: wrangler d1 execute tucaphe-db --file=./worker/seed.sql
-- Sau khi đã đồng bộ thật, đừng chạy lại file này (sẽ báo lỗi PRIMARY KEY trùng
-- — đó là chủ đích, để tránh vô tình ghi đè dữ liệu thật bằng dữ liệu demo).

INSERT INTO products (id, category_id, name, unit, icon, image, short_desc, description, specs, variants, retail_price, wholesale_price, wholesale_min_kg, stock, badge, visible) VALUES
('crema-blend', 'ca-phe', 'Crema Blend', 'kg', '🥣', 'https://images.pexels.com/photos/27860686/pexels-photo-27860686.jpeg?w=600', 'Pha trộn cân bằng, lớp crema dày, hợp pha máy espresso.', 'Công thức phối trộn theo tỷ lệ riêng của Tú Cà Phê, cho lớp crema dày và tách cà phê cân bằng giữa vị đậm và hương thơm.', NULL, '{"weight":["1kg","5kg","10kg","20kg"],"grind":["Hạt","Xay phin","Xay espresso"]}', 300000, 260000, 5, 200, 'Bán chạy', 1),
('honey-reserve', 'ca-phe', 'Honey Reserve', 'kg', '🍯', 'https://images.pexels.com/photos/16682442/pexels-photo-16682442.jpeg?w=600', 'Chế biến honey process, vị ngọt đậm, hương trái cây chín.', 'Cà phê chế biến theo phương pháp honey process, giữ lại một phần chất nhầy quả cà phê trong quá trình phơi, cho vị ngọt đậm và hương trái cây chín đặc trưng.', NULL, '{"weight":["1kg","5kg","10kg","20kg"],"grind":["Hạt","Xay phin","Xay espresso"]}', 350000, 275000, 5, 200, NULL, 1),
('phin-moc-ban', 'ca-phe', 'Phin Mộc Bản', 'kg', '☕', 'https://images.pexels.com/photos/3936163/pexels-photo-3936163.jpeg?w=600', 'Rang mộc nguyên chất, đậm đà, chuyên dùng pha phin.', 'Cà phê rang mộc nguyên chất, không tẩm phụ gia, rang theo mẻ nhỏ để giữ trọn hương vị đậm đà — chuyên dùng pha phin truyền thống.', NULL, '{"weight":["1kg","5kg","10kg","20kg"],"grind":["Hạt","Xay phin","Xay espresso"]}', 300000, 260000, 5, 200, NULL, 1),
('arabica-cau-dat', 'ca-phe', 'Arabica Cầu Đất', 'kg', '🌸', 'https://images.pexels.com/photos/2036874/pexels-photo-2036874.jpeg?w=600', 'Arabica vùng cao Cầu Đất, chua thanh, hương hoa trái.', 'Hạt Arabica trồng ở vùng cao Cầu Đất (Đà Lạt), rang vừa để giữ vị chua thanh đặc trưng cùng hương hoa và trái cây.', NULL, '{"weight":["1kg","5kg","10kg","20kg"],"grind":["Hạt","Xay phin","Xay espresso"]}', 450000, 400000, 5, 150, 'Cao cấp', 1),
('may-pha-compact-15', 'may-pha', 'Máy pha Espresso Compact 15', 'cái', '⚙️', NULL, 'Máy pha 1 group nhỏ gọn, phù hợp xe cà phê và quán take-away.', 'Máy pha espresso 1 group, kích thước nhỏ gọn, khởi động nhanh — phù hợp mô hình xe cà phê, take-away, quán nhỏ.', '{"Số group":"1","Áp suất bơm":"15 bar","Công suất":"1400W","Dung tích bình nước":"3L"}', NULL, 18000000, 18000000, 1, 20, 'Bán chạy', 1),
('may-pha-duo-2group', 'may-pha', 'Máy pha Espresso Duo 2 Group', 'cái', '⚙️', NULL, 'Máy pha 2 group công suất lớn, cho quán vừa và quán chuyên nghiệp.', 'Máy pha espresso 2 group, cấp nhiệt ổn định, đáp ứng sản lượng lớn cho quán vừa và quán chuyên nghiệp.', '{"Số group":"2","Áp suất bơm":"15 bar","Công suất":"3200W","Dung tích nồi hơi":"11L"}', NULL, 42000000, 42000000, 1, 10, NULL, 1),
('may-xay-chuyen-dung', 'may-xay', 'Máy xay cà phê chuyên dụng', 'cái', '🌀', NULL, 'Xay đều hạt, chỉnh độ mịn linh hoạt cho phin và espresso.', 'Máy xay lưỡi đĩa, chỉnh độ mịn linh hoạt, phù hợp xay cho pha phin lẫn pha máy espresso.', '{"Loại lưỡi":"Đĩa (flat burr)","Công suất":"250W","Tốc độ xay":"1.5g/s"}', NULL, 9500000, 9500000, 1, 15, NULL, 1),
('bo-dung-cu-pha-che-co-ban', 'thiet-bi', 'Bộ dụng cụ pha chế cơ bản', 'bộ', '🧰', NULL, 'Ca đánh sữa, cân điện tử, tamper, phin lọc — đủ bộ khởi đầu.', 'Bộ dụng cụ pha chế cơ bản gồm ca đánh sữa, cân điện tử, tamper, phin lọc — đủ trang bị khởi đầu cho một quầy pha chế.', '{"Số món":"8 món","Chất liệu chính":"Inox 304"}', NULL, 2800000, 2800000, 1, 30, NULL, 1);
